version: '3.8'

services:
  backend:
    build: ./backend
    container_name: {{ cookiecutter.project_name }}_backend
    ports:
      - "{{cookiecutter.port}}:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
