version: '3.8'

networks:
  {{ cookiecutter.project_name }}-net-dev:
    name: {{ cookiecutter.project_name }}-net-dev
    driver: bridge

services:
  backend:
    image: {{cookiecutter.docker_image_backend}}:${DOCKER_TAG:-latest}
    build: ./backend
    container_name: {{cookiecutter.docker_image_backend}}-dev
    restart: always
    ports:
      - "${PORT:-8000}:8000"
    env_file:
      - .env.dev
    volumes:
      - ./backend:/backend
    depends_on:
      - postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: >
      sh -c "uvicorn app:app --host ${HOST} --port 8000 --reload;"
    networks:
      - {{ cookiecutter.project_name }}-net-dev
  
  postgres:
    image: postgres:latest
    container_name: postgres-dev
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data-static:/var/lib/postgresql/data
    networks:
      - {{ cookiecutter.project_name }}-net-dev

volumes:
  db-data-static:
  backend:
