version: '3.8'

networks:
  {{ cookiecutter.project_name }}_net:
    name: {{ cookiecutter.project_name }}_net
    driver: bridge

services:
  backend:
    image: {{cookiecutter.docker_image_backend}}:latest
    build: ./backend
    container_name: {{cookiecutter.docker_image_backend}}
    restart: always
    ports:
      - "${PORT:-8000}:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/backend
    networks:
      - {{ cookiecutter.project_name }}_net
